apiVersion: v1
kind: PersistentVolume
metadata:
  name:
  namespace:
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage:
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:
