apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongodb
        imagePullPolicy: IfNotPresent
        command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        volumeMounts:
          - mountPath: /data
            name: mongodb
        ports:
          - containerPort: 27017
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: mongodb-pvc
