apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  namespace: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: distributor
        image: python
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        volumeMounts:
          - mountPath: /python
            name: python
      volumes:
      - name: python
        persistentVolumeClaim:
          claimName: python-pvc
