apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: ""
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql-pvc
