apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "1234"
#        volumeMounts:
#          - mountPath:
#            name: postgres
#      volumes:
#      - name: postgres
#        persistentVolumeClaim:
#          claimName: postgres-pvc
