apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus3-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nexus-data"
